osumb/challenges

app.js
config.js
controllers/Performance.js
controllers/StaticPages.js
models/Performance.js
models/setup.js
package.json
routes/routes.js
views/index.handlebars
views/layouts/main.handlebars
views/performance.handlebars

Right now, just created a performance model with a slight db set up script for Heroku

Data models

---

.eslintignore
.travis.yml
app.js
controllers/StaticPages.js
package.json
test/PerformanceControllerTest.js

We use server side rendering, so we have to render the templates with mocked data and compare to the response text to see if the page is the same

Added tests (kind of) for the performances controller

---

bin/www
controllers/Performance.js
models/Performance.js

Fixed error on npm start. For controller tests, we needed to start the server, app.js was changed. That broke bin/www, so that's fixed.

Heroku was broken

---

.travis.yml

Only node js 5 specified in .travis.yml

---

models/setup.js

Add user with admin role to play around with that

Added Chris Hoch (admin role) to db setup script

---

controllers/Challenges.js
controllers/Performance.js
controllers/Users.js
routes/routes.js
views/layouts/main.handlebars
views/partials/challengeablePeople.handlebars

Changed up routing a little bit. See routes/routes.js to see 'convention'. The routes don't do anything yet. They're just laid out

Url structure

---

docs/ChallengeLogic.md

We're putting documentation into source control ✨  💖

[WIP] Documentation

---

docs/ChallengeLogic.md

Fixed challenges readme

---

docs/Deployment

Added some Heroku docs

---

controllers/Users.js
views/partials/currentChallenge.handlebars
views/partials/results.handlebars
views/userProfile.handlebars

Fixed user profile bug

---

app.js
models/schema.sql
package.json

Why Heroku no work?

---

controllers/Performances.js
controllers/Users.js
models/Performance.js
package.json

Finish sequelize

---

controllers/Performances.js
controllers/Users.js
models/Challenge.js
models/Performance.js
models/Result.js

Consistent naming convention

---

controllers/StaticPages.js
controllers/Users.js
db/schema.sql
db/setup.js
middleware/index.js
models/Performance.js
routes/routes.js
spec/fixtures/fakePerformances.js
views/partials/challengeWindow.handlebars

Current performance flag

---

.eslintignore
.gitignore
auth/index.js
controllers/Performances.js
controllers/Results.js
db/queries/index.js
db/queries/results-for-eval.sql
db/queries/results-for-performance-query.sql
db/queries/results-query.sql
db/schema.sql
middleware/index.js
models/Challenge.js
models/Performance.js
models/Result.js
models/Spot.js
models/User.js
routes/routes.js
script/test
spec/queryBuilderSpec.js
utils/db.js
views/challengesForEval.handlebars
views/partials/page/navbar.handlebars
views/resultsForPerformance.handlebars

The goal of this is to handle the majority of squad leader facing things

Sl challenge stuff

---

controllers/Challenges.js
controllers/Users.js
routes/routes.js
views/partials/currentChallenge.handlebars
views/partials/page/navbar.handlebars

Move new challenge route

---

views/partials/page/user-navbar.handlebars

Fix two broken links

---

utils/email.js
views/emails/challenge-signup-confirmation.handlebars

Email template

---

controllers/StaticPages.js
models/Performance.js

Change homepage next performance query

---

public/js/challenges/challenge-select.js

The most important part of the app was broken by one character...

Challenge Select 404

---

public/stylesheets/style.scss

```bash
tarebyte [~/src/osumb/challenges] [master]
-> % npm run dev
> challenges@1.0.0 dev /Users/tarebyte/src/osumb/challenges
> webpack && NODE_ENV=dev nodemon --use_strict ./bin/www
Hash: a104dc80c63622b6bee7
Version: webpack 1.13.1
Time: 2452ms
Asset    Size  Chunks             Chunk Names
bundle.js  107 kB       0  [emitted]  main
+ 24 hidden modules
ERROR in ../~/css-loader!./stylesheets/style.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./users/make-ineligible.scss in /Users/tarebyte/src/osumb/challenges/public/stylesheets
@ ../~/css-loader!./stylesheets/style.scss 6:10-92
ERROR in ./stylesheets/style.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./users/make-ineligible.scss in …
```

Remove unused stylesheet

---

controllers/Results.js
db/queries/results-for-eval.sql
models/Challenge.js
models/Result.js
models/User.js

Fixes #128 
`Challenges.findAllChallengeablePeopleForUser` checks for performance id and doesn't make a query if not given one.
`Result.findAllForEval` query joins on performances with a closed challenge window

Current performance

---

db/schema.sql

Really dumb bug

---

public/js/results/approve.js
public/stylesheets/results/approve.scss
views/results/approve.handlebars

Results approve

---

public/js/users/manage.js
public/style.scss
public/stylesheets/header.scss
public/stylesheets/users/search.scss
views/layouts/main.handlebars
views/partials/page/title.handlebars
views/users/manage.handlebars

Cut the things from bootstrap that made this look decently nice. It now looks the same

Styling search

---

public/style.scss
public/stylesheets/results/evaluation.scss
views/results/show-for-evaluation.handlebars

Styling for sl evaluation forms

---

views/users/individual-manage.handlebars

If there is no upcoming performance, just don't render the ability to make manage actions. Also include an explanation as to why

Views: check for performance before rendering manage user page

---

controllers/Users.js
models/Performance.js
public/style.scss
public/stylesheets/partials/challenge-window.scss
public/stylesheets/users/show-admin.scss
public/stylesheets/users/show.scss
views/partials/challenge-window.handlebars
views/users/admin.handlebars
views/users/show.handlebars

Upcoming performance

---

controllers/Results.js
db/queries/results-for-eval.sql
db/schema.sql
models/Result.js

Change SL eval permission

---

script/setup

Start redis server in script/setup

---

controllers/Users.js
models/User.js
public/js/users/index.js
public/js/users/settings.js
public/style.scss
public/stylesheets/navbar.scss
public/stylesheets/users/settings.scss
routes/routes.js
views/partials/page/navbar.handlebars
views/users/settings.handlebars

The title is pretty self-explanatory

Change password

---

auth/index.js
controllers/Users.js
db/schema.sql
db/setup.js
models/User.js
public/js/users/settings.js
routes/routes.js
views/users/settings.handlebars

This was pretty simple to implement

Password middleware

---

auth/index.js
controllers/Users.js
db/schema.sql
db/setup.js
models/User.js
public/js/users/index.js
public/js/users/settings.js
public/style.scss
public/stylesheets/navbar.scss
public/stylesheets/users/settings.scss
routes/routes.js
views/partials/page/navbar.handlebars
views/users/settings.handlebars

/cc @tarebyte 
Turns out this was pretty simple

Force password update

---

utils/email.js
views/emails/challenge-list.handlebars

Really simple email template for challenge list email because plain text is boring

Email templates

---

utils/logger.js

Error logger won't send email in test mode

---

controllers/Challenges.js
controllers/Users.js
db/queries/can-challenge-for-performance.sql
db/queries/challengeable-people.sql
db/queries/results-query.sql
models/Challenge.js
models/Result.js
views/challenges/new.handlebars

If the user has a result for the challenge, don't display it on the profile

Challenge view

---

experiments/GitHubGistUserCreator.js
models/User.js
package.json
spec/fixtures/utils/index.js
utils/email.js

Title says it all, this uses the GitHub API to pull down a given gist, parse the file, and then create the users and email them.
You need to add 2 environment variables for this.
`GITHUB_TOKEN`
`GITHUB_GIST_ID`
/cc @atareshawty

Create users from GitHub Gist

---

public/js/utils/challenge-window.js
views/partials/challenge-window.handlebars

Display closing time when challenge window is open

---

db/schema.js
package.json
script/schema

Script to just set up the db schema

---

script/schema

Fix script

---

experiments/GitHubGistUserCreator.js

And check for no spotId (admin)

console.log email information for sanity check

---

controllers/Users.js

This is the fix, but I don't want to do a deploy until we're done

Get first member of User.canChallengeForPerformance

---

controllers/Users.js
models/User.js
public/js/users/index-member.js
public/js/users/index.js
public/js/utils/index.js
public/js/utils/valid-spot.js
public/style.scss
public/stylesheets/navbar.scss
public/stylesheets/users/index.scss
routes/routes.js
views/index.js
views/partials/page/admin-navbar.handlebars
views/users/index.handlebars

- Manually updating user spot id incase things get weird (things have already gotten weird)

Manual spot change

---

controllers/Results.js

Fixes bug where results get switched every time results get approved

Destructure array in results controller

---

controllers/Users.js
models/User.js
public/js/users/index-member.js
public/js/users/settings.js
public/stylesheets/users/index.scss
routes/routes.js
views/users/index.handlebars

Manual part change

---

models/Result.js

Change performanceResultMap into an array rather than plain object

---

public/stylesheets/results/evaluation.scss

This fixed some issue on prod that has somehow presented itself after it worked the first two times

Give min height for .ResultsEvaluation

---

.eslintrc.json
auth/index.js
controllers/Users.js
db/queries/can-challenge-for-performance.sql
models/Challenge.js
models/Result.js
models/User.js
public/components/challenge-window.jsx
public/components/challenge-window.scss
public/components/profile.jsx
public/components/profile.scss
public/components/result.jsx
public/components/result.scss
public/components/results.jsx
public/style.scss
public/utils/api.js
routes/routes.js

Recreating the profile page!
I added a few styling modifications to make mobile better

Profile page

---

controllers/Challenges.js
controllers/Users.js
models/Challenge.js
public/components/challenge-select.jsx
public/components/challenge-select.scss
public/components/challengeable-user.jsx
public/components/challengeable-users.jsx
public/components/challengeable-users.scss
public/index.jsx
public/utils/api.js
routes/routes.js

Challenge select

---

auth/index.js
controllers/Results.js
models/Result.js
public/components/banner.jsx
public/components/banner.scss
public/components/challenge-select.jsx
public/components/challenges-dropdown.jsx
public/components/navbar.jsx
public/components/result-for-evaluation.jsx
public/components/result-for-evaluation.scss
public/components/results-for-evaluation.jsx
public/components/results-for-evaluation.scss
public/index.jsx
public/style.scss
public/utils/auth.js
routes/routes.js
spec/4-squad-leader-eval-spec.js

Results evaluate

---

client/src/profile/user-header.jsx

client: make user header spotId text smaller

---

client/src/App.js
client/src/challenge/challenge-evaluations.jsx
client/src/challenge/challenge-select.jsx
client/src/challenge/current-challenge.jsx
client/src/challenge/user-comparison.jsx
client/src/shared-components/desktop-nav.jsx
client/src/shared-components/link-dropdown.jsx
client/src/shared-components/login.jsx
client/src/shared-components/mobile-nav.jsx
client/src/shared-components/navbar.jsx

Change all `onClick` events to `onTouchTap` to avoid delays to triggering `onClick` events on mobile.

Touch events

---

api/controllers/results-controller.js
api/models/result-model.js
client/src/App.js
client/src/result/completed-result.jsx
client/src/result/completed-result.scss
client/src/result/completed-results.jsx
client/src/result/completed-results.scss
client/src/utils/routes.js
config/routes.js
db/queries/results-index.sql

This type of result has been approved. The only fields that can be edited is `firstComments` and `secondComments`. That's what's being loaded and edited in this PR.
* Works on staging!

Past results

---

api/controllers/results-controller.js
api/models/result-model.js
client/src/App.js
client/src/result/completed-result.jsx
client/src/result/pending-result.jsx
client/src/result/pending-result.scss
client/src/result/pending-results.jsx
client/src/result/pending-results.scss
client/src/utils/routes.js
config/routes.js
db/queries/results-for-approval.sql

You can approve and edit winner and comments before approval
* Works on staging

Approve results

---

client/src/profile/profile.jsx
client/src/shared-components/error-banner.jsx
client/src/shared-components/error-banner.scss
client/src/shared-components/navbar.jsx
client/src/user/roster-item.jsx
client/src/utils/api-wrapper.jsx
client/src/utils/api.js
client/src/utils/error-emitter.js
client/src/utils/index.js

Render a error message component (with is triggered with an event). Called by api util

Client error messages

---

bin/create-react-app
client/src/index.js
package.json

That and I updated homebrew, so foreman (formerly with heroku toolbelt) was removed. The command was changed to `heroku local -f Procfile.dev` to run the dev server. That is all. This only affects dev, so no need to check on production or anything

WE NOW HAVE HOT MODULE RELOADING!!!

---

.travis.yml
test/factories/challenges.rb

@atareshawty I _think_ this should solve your travis database woes.

Set RAILS_ENV globally and use db:reset

---

package.json
yarn.lock

React router finally released

---

app/models/challenge.rb
app/models/challenge/bylder.rb
spec/models/challenge/builder_spec.rb
spec/models/challenge_spec.rb

Attempting to use the builder pattern to take a lot of logic out of the challenge controller.
And adding the fact that there are rows that can't participate in tri challenges

Rails: add ChallengeBylder

---

app/controllers/application_controller.rb
app/controllers/discipline_actions_controller.rb
app/controllers/performances_controller.rb
app/controllers/users_controller.rb
app/views/discipline_actions/show.json.jbuilder
app/views/performances/next.json.jbuilder
app/views/users/show.json.jbuilder
config/routes.rb
spec/requests/discipline_actions_spec.rb
spec/requests/performances_spec.rb

Create ensure_admin! as ApplicationController action
Created DisciplineActionsController along with json views and tests

Rails: backend changes for profile admin view

---

app/controllers/performances_controller.rb
app/views/performances/index.json.jbuilder
config/routes.rb
spec/requests/performances_spec.rb

PerformanceController

---

app/controllers/performances_controller.rb
app/models/performance.rb
client/src/App.jsx
client/src/components/flex/components/flex_child.jsx
client/src/components/performance/index.jsx
client/src/components/performance/index.scss
client/src/components/textfield/index.jsx
client/src/data/performance/helpers.js
client/src/scenes/performance/create/index.jsx
client/src/scenes/performance/index/index.jsx
spec/requests/performances_spec.rb

Mostly front end updates for performance#index component. You can now update the challenge window (and other things) of performances from the UI

Performance ui

---

app/controllers/performances_controller.rb
client/src/components/performance/index.jsx
client/src/data/performance/helpers.js
client/src/scenes/performance/index/index.jsx
client/src/utils/api.js
config/routes.rb
spec/requests/performances_spec.rb

Ability to delete a performance and better layout for the `performances/all`

Performance index

---

package.json

There was a security threat found in everything below the version this PR switches to

Update node version because Heroku told me to

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/middleware/new_token_middleware.rb
app/models/user.rb
bin/client_install
client/src/utils/api.js
client/src/utils/auth.js
config/application.rb
db/migrate/20170711043231_add_revoke_token_date_to_users.rb
db/schema.rb

Add middleware to issue new tokens on successful requests and add client side auth flow

Authentication

---

app/controllers/user_challenges_controller.rb
app/models/challenge.rb
app/models/result.rb
app/models/user_challenge.rb
app/models/user_challenge/evaluator.rb
app/views/challenges/_challenge.json.jbuilder
config/routes.rb
db/migrate/20170724044933_move_winners_to_user_challenge.rb
db/schema.rb
lib/seed/challenges.rb
spec/factories/users.rb
spec/models/challenge_spec.rb
spec/models/result.rb
spec/models/user_challenge/evaluator_spec.rb
spec/requests/user_challenge_evaluation_spec.rb

@atareshawty let me know what you think about the direction of this so far
Also, how much do you want this broken up? It's already getting big and this isn't even in the API yet.

Challenge Evaluations API

---

app/controllers/user_challenges_controller.rb
app/models/user_challenge/destroyer.rb
spec/models/user_challenge/destroyer_spec.rb
spec/requests/user_challenges_spec.rb

~~**Note: this is waiting for #303 to be merged. After that I'll rebase this!**~~

Boyscouting

---

app/controllers/challenges_controller.rb
app/controllers/user_challenges_controller.rb
app/models/challenge.rb
app/models/user_challenge.rb
app/views/challenges/_challenge_for_evaluation.json.jbuilder
app/views/challenges/for_evaluation.json.jbuilder
app/views/user_challenges/_user_challenge_for_evaluation.json.jbuilder
config/routes.rb
spec/models/challenge_spec.rb
spec/requests/challenge_evaluations_spec.rb
spec/requests/user_challenge_evaluation_spec.rb
spec/support/shared_examples/challenge.rb

This adds some additional endpoints that I need for the front end and fixes a nasty authorization bug (I'll point out the line)

Challenge Evaluations API Additions

---

app/controllers/challenges_controller.rb
app/mailers/challenge_success_mailer.rb
app/models/spot.rb
app/views/challenge_success_mailer/challenge_success_email.html.erb
spec/mailers/previews/challenge_success_mailer_preview.rb
spec/mailers/previews/password_reset_mailer_preview.rb
spec/models/spot_spec.rb

Email the challenger on challenge creation

---

app/views/user_challenges/_user_challenge.json.jbuilder
app/views/users/profile.json.jbuilder
bin/rails_c
client/src/components/user_challenge/index.jsx
client/src/data/challenge_evaluations/propTypes.js
client/src/scenes/user/profile/components/challenge.jsx
client/src/scenes/user/profile/components/member_profile.jsx
client/src/scenes/user/profile/index.jsx

Challenges in profile

---

app/controllers/challenges_controller.rb
spec/requests/challenge_evaluations_spec.rb

Rails: filter challenges that have windows still open for evaluation

---

app/controllers/challenges_controller.rb
client/src/components/button/index.jsx
client/src/data/challenge/helpers.js
client/src/scenes/challenge/approval/components/challenge.jsx
client/src/scenes/challenge/approval/index.jsx
config/routes.rb
spec/requests/challenge_change_stage_spec.rb

This just adds a 'disapprove' button to challenges to send them back to eval stage
/cc @kylekthompson This touches the same component you're using in #326

Challenge disapprove

---

app/controllers/challenges_controller.rb
app/controllers/user_challenges_controller.rb
app/models/challenge.rb
client/src/App.jsx
client/src/components/challenge/components/challenge.jsx
client/src/components/challenge/index.jsx
client/src/components/side_nav/components/side-nav-item.jsx
client/src/components/side_nav/components/side-nav.jsx
client/src/components/side_nav/index.js
client/src/components/snackbar/index.jsx
client/src/components/user_challenge/index.jsx
client/src/data/challenge/helpers.js
client/src/data/challenge_evaluations/helpers.js
client/src/scenes/challenge/approval/index.jsx
client/src/scenes/challenge/evaluations/index.jsx
client/src/scenes/results/completed/index.jsx
config/routes.rb
spec/models/challenge_spec.rb
spec/requests/challenge_completed_spec.rb
spec/requests/user_challenge_comment_updates_spec.rb

Challenge Results

---

app/mailers/challenge_success_mailer.rb
client/src/components/challenge/components/challenge.jsx
client/src/components/navbar/components/error-banner.jsx
client/src/components/user_challenge/index.jsx
client/src/scenes/performance/challenge_select/components/challenge_select.jsx
client/src/scenes/performance/index/index.jsx
client/src/scenes/user/profile/components/challenge.jsx
client/src/utils/error-emitter.js

closing ErrorBanner emits an event so components can change state

Front end cleanup

---

app/controllers/challenges_controller.rb

Just to be able to search for these logs and get detailed events

Log attempted challenge creation along with success/failure

---

app/views/users/profile.json.jbuilder

Hide Challenge

---

app/controllers/application_controller.rb
app/controllers/password_reset_requests_controller.rb
app/controllers/performances_controller.rb
app/controllers/user_challenges_controller.rb
app/controllers/users_controller.rb
spec/models/user_spec.rb
spec/requests/password_reset_requests_spec.rb

Fixes #336 
I just did a regex search for `params.*buck_id`. I'll do another pass to make sure I got all of them though.

Downcase buck_id when we get it from params

---

app/models/challenge/bylder.rb
spec/models/challenge/bylder_spec.rb

Fix Tri Challenge

---

app/models/challenge/bylder.rb
spec/models/challenge/bylder_spec.rb

Fix joining open spot challenge bug

---

db/migrate/20170906022328_add_unique_performance_and_spot_for_challenge.rb
db/schema.rb
spec/models/challenge_spec.rb

Add unique index on challenge for spot and performance

---

app/models/challenge.rb
spec/models/challenge_spec.rb

Fix User Challenge Permissions

---

.env.example
Gemfile.lock
app/mailers/challenge_list_mailer.rb
app/models/challenge/list_builder.rb
app/models/spot.rb

Fixes Challenge::ListBuilder#build_challenge_list

---

app/models/challenge.rb
spec/models/challenge_spec.rb

Fixes #368

---

app/models/challenge/list_builder.rb
lib/tasks/scheduler.rake

Fixes bug with challenge list builder

---

config/application.rb

Reduce logs from jbuilder

---

app/controllers/performances_controller.rb
app/services/performance_service.rb
client/src/components/performance/index.jsx
client/src/data/performance/helpers.js
client/src/scenes/performance/index/index.jsx
config/routes.rb
spec/requests/performances_spec.rb

Email Challenge List Button

---

client/src/data/spot/helpers.js

React: fixes bug with switching spots in K row

---

app/controllers/performances_controller.rb
app/jobs/queue_new_performance_emails_job.rb
app/mailers/new_performance_mailer.rb
app/models/user.rb
app/services/performance_service.rb
app/views/new_performance_mailer/new_performance_email.html.erb
spec/mailers/previews/new_password_mailer_preview.rb
spec/requests/performances_spec.rb
spec/services/performance_service_spec.rb

Adds new performance email when performance is created

---

app/controllers/spots_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/models/user/loader.rb
app/services/password_reset_request_service.rb
app/services/password_service.rb
app/services/spot_service.rb
app/services/user_service.rb
app/views/spots/find.json.jbuilder
config/routes.rb
db/migrate/20171015165446_add_active_to_user.rb
db/schema.rb
lib/sql/performance/challengeable_users.sql
spec/factories/users.rb
spec/requests/user_creation_spec.rb
spec/services/password_reset_request_service_spec.rb
spec/services/password_service_spec.rb
spec/services/spot_service_spec.rb
spec/services/user_service_spec.rb

This is the backend work of #396. Splitting this out here to it's easier to review

User creation backend

---

client/src/App.jsx
client/src/components/challenge/components/done_challenge.jsx
client/src/data/challenge/propTypes.js
client/src/data/user_challenge/helpers.js
client/src/data/user_challenge/propTypes.js
client/src/scenes/user/roster/index.jsx

Instead of it reporting that everyone lost their challenge, the admin view for a user's profile reports the user's place in a challenge

Fix admin profile bug

---

client/src/data/challenge/helpers.js
client/src/data/challenge/propTypes.js
client/src/data/user/helpers.js
client/src/scenes/results/completed/index.jsx

This reverts commit 8c6921b600ca24768e49e2671c3b885dae0788fd.

Revert "Adds performance challenge results csv download"

---

app/controllers/index_controller.rb
client/public/robots.hide.txt
client/public/robots.show.txt
config/routes.rb

Need to add the environment variable: `DISABLE_ROBOTS`

Adds robots.txt for different environments

---

.travis.yml
client/package.json
client/src/components/discipline_action/components/current.jsx
client/src/scenes/challenge/evaluations/components/place-picker.jsx
client/src/scenes/password_reset/reset/index.jsx
client/src/scenes/user/roster/components/edit_first_name.jsx
client/src/scenes/user/roster/components/edit_last_name.jsx

Correctly run eslint

---

Gemfile.lock

Updates sinatra

---

app/assets/stylesheets/application.css
app/assets/stylesheets/users/profile.css
app/controllers/application_controller.rb
app/helpers/performance_helper.rb
app/views/layouts/application.html.erb
app/views/performances/_next.html.erb
app/views/sessions/show.html.erb
app/views/users/_admin_profile.html.erb
app/views/users/_profile.html.erb
app/views/users/_user_header.html.erb

[Trello](https://trello.com/c/TSdk6g0q/1-admin-profile)

Admin profile

---

app/assets/stylesheets/application.css
app/assets/stylesheets/challenges/challenge.css
app/assets/stylesheets/challenges/current_challenge.css
app/assets/stylesheets/discipline_actions/_discipline_action.css
app/assets/stylesheets/user_challenges/user_challenge.css
app/assets/stylesheets/users/profile.css
app/controllers/sessions_controller.rb
app/controllers/user_challenges_controller.rb
app/models/user.rb
app/models/user_challenge.rb
app/views/challenges/_challenge.html.erb
app/views/challenges/_current_challenge.html.erb
app/views/discipline_actions/_discipline_action.html.erb
app/views/user_challenges/_user_challenge.html.erb
app/views/users/_performer_profile.html.erb
app/views/users/_profile.html.erb
config/locales/en.client_messages.yml
config/routes.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/user_challenges_controller_spec.rb

[Trello Card](https://trello.com/c/4IaepJ6i/2-user-profile)
I elected to get rid of the emoji for 1st, 2nd, 3rd place. Didn't seem worth it

User profile

---

app/assets/stylesheets/challenges/evaluate.css
app/controllers/challenges_controller.rb
app/models/challenge.rb
app/services/challenge_service.rb
app/services/user_challenge_service.rb
app/services/user_service.rb
app/views/challenges/_evaluation.html.erb
app/views/challenges/evaluate.html.erb
config/locales/en.client_messages.yml
config/locales/en.errors.yml
config/routes.rb
spec/controllers/challenges_controller_spec.rb
spec/models/challenge_spec.rb
spec/services/challenge_service_spec.rb
spec/services/user_challenge_service_spec.rb

[Trello](https://trello.com/c/83CShL7E/5-evaluate-challenge)
This PR reimplements challenge evaluation

Evaluate challenge

---

app/assets/stylesheets/challenges/completed.css
app/controllers/challenges_controller.rb
app/helpers/router.rb
app/views/challenges/_completed.html.erb
app/views/challenges/completed.html.erb
config/routes.rb
spec/controllers/challenges_controller_spec.rb
spec/factories/challenges.rb

[Trello](https://trello.com/c/cbNw5ao4/6-completed-results)

Completed results

---

app/controllers/users_controller.rb
app/views/users/show.html.erb
spec/controllers/users_controller_spec.rb

Get all `:done` challenges to show admin. Confirmed this works in prod

Users#show bug fix

---

app/assets/stylesheets/users/show.css
app/controllers/users_controller.rb
app/views/users/show.html.erb

Fixes spacing issues for user with many challenges in users#show

---

app/assets/stylesheets/users/show.css
app/controllers/application_controller.rb
app/controllers/discipline_actions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/services/user_service.rb
app/views/users/show.html.erb
config/locales/en.client_messages.yml
config/routes.rb
spec/controllers/users_controller_spec.rb

[Trello](https://trello.com/c/aOWNojC6/13-admin-user-view)

Individual User Management

---

app/controllers/reset_data_controller.rb
app/controllers/users_controller.rb
app/views/users/upload.html.erb
config/locales/en.client_messages.yml
config/routes.rb
spec/controllers/users_controller_spec.rb

[Trello](https://trello.com/c/puq2ASBB/11-user-upload)

User upload

---

app/assets/stylesheets/users/new.css
app/controllers/users_controller.rb
app/services/user_creation_service.rb
app/views/users/new.html.erb
config/locales/en.client_messages.yml
config/routes.rb
spec/controllers/users_controller_spec.rb
spec/services/user_creation_service_spec.rb

[Trello](https://trello.com/c/2UEm5sm2/12-user-create)

User create

---

app/assets/stylesheets/password_reset_requests/new.css
app/assets/stylesheets/password_reset_requests/show.css
app/assets/stylesheets/sessions/new.css
app/controllers/password_reset_requests_controller.rb
app/views/password_reset_requests/new.html.erb
app/views/password_reset_requests/show.html.erb
app/views/sessions/new.html.erb
config/locales/en.client_messages.yml
config/routes.rb
spec/controllers/password_reset_requests_controller_spec.rb

[Trello](https://trello.com/c/KY6quMZj/23-password-reset)

Password reset

---

app/views/challenges/completed.html.erb

How people are naming performances makes the phrasing a little weird

Removes a word from /challenges/completed
